#API list

@rootUrl = http://localhost:3000

### Check server status
GET {{rootUrl}}

### post user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"subekshya",
    "lName":"kharel",
    "email":"subekshyakharel922@gmail.com",
    "phone":12344,
    "password":"123"
}

### login user
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"subekshyakharel922@gmail.com",
    "password":"123"
}

### get user profile
GET {{rootUrl}}/api/v1/users/profile
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NTU1NzU0NjQsImV4cCI6MTc1NTY2MTg2NH0.8MGR_wFfiSAOxFXvPhUTaa62VW4DpBTmfh8kVHyxlZw

### renew jwt
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NTU1ODEyNjEsImV4cCI6MTc1ODE3MzI2MX0.ZxYvAg43J_0rDzSEWTyXOzhumT_jP_Hbgc4fLlulT8U


#### =============order api ==========
### insert ordered product
POST {{rootUrl}}/api/v1/order
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NTU1OTAwNjUsImV4cCI6MTc1NTY3NjQ2NX0.fwoYoupGFQCgmhNQqcg-0_UWxlUqQLzp80TruGyL9lE

[
    {
        "productId":"689f4ffb8ebc7c64e6f1b8d1",
        "thumbnail":"https://res.cloudinary.com/dgjcfs1qn/image/upload/v1755271018/products/xyalbibwcwuw5omzpmyt.png",
        "productTitle":"Denim skirt",
        "productSlug":"denim-skirt"
    }
]

### get order product
GET {{rootUrl}}/api/v1/order
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NTg2MDA0MTAsImV4cCI6MTc1ODY4NjgxMH0.21Gpq4mBOMBC1kG1R3QNjtai6KT7iAa8bobdIRmk4LY

### Get all order product 
GET {{rootUrl}}/api/v1/order/all-order

### update order status
PATCH {{rootUrl}}/api/v1/order/68d7466bbc81078028cc16f2
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NjY0OTEyMzcsImV4cCI6MTc2NjU3NzYzN30.9VkqepWiSIaBSs4TYYnb_n6v9RxINSNDqsFwp4kxy3Y
Content-Type: application/json

{
  "status": "processing"
}

### delete order
DELETE {{rootUrl}}/api/v1/order/694a72b6e61ad5939ed16adc
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NjcwMTM3MjcsImV4cCI6MTc2NzEwMDEyN30.D4IbMiHwSnMO_SdcB7mYgL6F1GOlepZhB4Qac0EMNQU


##############review section ############
###insert review
POST {{rootUrl}}/api/v1/review/
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN1YmVrc2h5YWtoYXJlbDkyMkBnbWFpbC5jb20iLCJpYXQiOjE3NjY5MjY0MjUsImV4cCI6MTc2NzAxMjgyNX0.oa8XFRapRFVYy_rU8kCG8ebNAY8p1Z57Drq3IiindNU
Content-Type: application/json

{
    "productId":"68cf7a9e80f69650f55b47ad",
    "orderId":"68d7466bbc81078028cc16f2",
    "title":"review product",
    "reviewMessage":"I have review this product",
    "rating":3.4
}

### get single product Reviews
GET {{rootUrl}}/api/v1/review/68cf7a9e80f69650f55b47ad

### get All the product with reviews
GET {{rootUrl}}/api/v1/order/getProductReview

